const $=id=>document.getElementById(id),API='https://tltrbkttwzvwghaplurl.supabase.co/functions/v1/algorithm-lab';
let token=sessionStorage.getItem('dju-algolab-admin')||'',students=[],section='all',detail=null,choices=[],passwordMode='admin',refreshing=false;
async function request(action,body={}){const response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action,...body}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok){if(response.status===401&&action!=='admin-login')signOut();throw Error(data.error||'요청 실패');}return data;}
function signOut(){token='';students=[];detail=null;choices=[];sessionStorage.removeItem('dju-algolab-admin');$('admin-workspace').hidden=true;$('admin-login-panel').hidden=false;for(const d of document.querySelectorAll('dialog[open]'))d.close();for(const id of ['student-rows','join-codes','detail-title','detail-summary','detail-grid','submission-code','submission-report','submission-select'])$(id).replaceChildren();}
function filtered(){const query=$('student-search').value.trim().toLowerCase(),state=$('progress-filter').value;return students.filter(s=>(section==='all'||s.section===section)&&(!query||(s.student_no+' '+s.name).toLowerCase().includes(query))&&(state==='all'||(state==='not-started'&&s.solved===0)||(state==='working'&&s.solved>0&&s.solved<12)||(state==='complete'&&s.solved===12)));}
function time(value){return new Date(value).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
function render(){
 const rows=filtered();$('student-rows').replaceChildren();$('stat-students').textContent=rows.length+'명';$('stat-average').textContent=(rows.length?rows.reduce((n,s)=>n+s.solved,0)/rows.length:0).toFixed(1)+' / 12';$('stat-complete').textContent=rows.filter(s=>s.solved===12).length+'명';$('stat-attempts').textContent=rows.reduce((n,s)=>n+s.attempts,0)+'회';
 for(const student of rows){const tr=document.createElement('tr');const cell=text=>{const td=document.createElement('td');td.textContent=text;tr.append(td);return td;};cell(student.section+'반');const person=cell(student.student_no);const name=document.createElement('strong');name.textContent=student.name;person.append(name);const progress=cell(student.solved+' / 12');const track=document.createElement('div');track.className='student-progress';const fill=document.createElement('div');fill.style.width=student.solved/12*100+'%';track.append(fill);progress.append(track);cell(student.attempts+'회');cell(student.current_problem+' · '+(student.current_language==='c'?'C':'Python'));cell(time(student.last_seen));const action=cell('');const button=document.createElement('button');button.textContent='이력 · 코드';button.onclick=()=>openStudent(student.id);action.append(button);$('student-rows').append(tr);}
 $('admin-empty').hidden=rows.length>0;$('admin-empty').textContent=students.length?'조건에 맞는 학생이 없습니다.':'아직 등록한 학생이 없습니다. 학생들에게 해당 반의 참여 코드를 안내하세요.';
}
async function refresh(){if(refreshing||!token)return;const activeToken=token;refreshing=true;$('admin-refresh').disabled=true;try{const data=await request('admin-dashboard');if(token!==activeToken)return;students=data.students;$('updated-at').textContent='최근 갱신 '+new Date(data.updated_at).toLocaleTimeString('ko-KR');$('join-codes').textContent='01반: '+data.join_codes['01']+'\n02반: '+data.join_codes['02'];$('admin-status').textContent='';render();}catch(error){$('admin-status').textContent=error.message;}finally{refreshing=false;$('admin-refresh').disabled=false;}}
$('admin-login-form').onsubmit=async event=>{event.preventDefault();$('admin-login-submit').disabled=true;try{const data=await request('admin-login',{password:$('admin-password').value});token=data.token;sessionStorage.setItem('dju-algolab-admin',token);$('admin-password').value='';$('admin-login-panel').hidden=true;$('admin-workspace').hidden=false;await refresh();}catch(error){$('admin-login-error').textContent=error.message;}finally{$('admin-login-submit').disabled=false;}};
$('admin-logout').onclick=async()=>{try{await request('logout');}catch{}signOut();};
for(const button of document.querySelectorAll('[data-section]'))button.onclick=()=>{section=button.dataset.section;for(const b of document.querySelectorAll('[data-section]'))b.setAttribute('aria-pressed',String(b===button));render();};
$('student-search').oninput=render;$('progress-filter').onchange=render;$('admin-refresh').onclick=refresh;
setInterval(()=>{if(token&&$('admin-auto').checked&&!document.hidden)refresh();},10000);
async function openStudent(id){
 const activeToken=token;detail=null;choices=[];
 $('student-detail').showModal();$('detail-title').textContent='불러오는 중…';$('detail-summary').textContent='';$('submission-code').textContent='';$('detail-grid').replaceChildren();$('submission-select').replaceChildren();$('submission-report').replaceChildren();
 try{const response=await request('admin-student',{student_id:id});if(token!==activeToken)return;detail=response;const s=detail.student;$('detail-title').textContent=s.section+'반 · '+s.student_no+' '+s.name;$('detail-summary').textContent='최근 제출 200건과 언어별 저장 초안 · 제출 시각은 서버 접수 기준';const summary=students.find(row=>row.id===id);
 for(let n=1;n<=12;n++){const p='P'+String(n).padStart(2,'0'),box=document.createElement('div'),title=document.createElement('strong');title.textContent=p;box.append(title);for(const language of ['python','c']){const status=summary?.problems.find(item=>item.problem===p&&item.language===language),line=document.createElement('div');line.textContent=(language==='c'?'C':'Python')+': '+(status?.solved?'✓ 통과':status?'진행 중':'미제출');box.append(line);}$('detail-grid').append(box);}
 choices=[...detail.submissions.map(s=>({...s,kind:'submit'})),...detail.drafts.map(d=>({...d,kind:'draft'}))];for(const [i,item] of choices.entries()){const option=document.createElement('option');option.value=i;option.textContent=`${item.problem} · ${item.language} · ${item.kind==='draft'?'저장된 초안':item.solved?'통과':item.passed+'/'+item.total} · ${time(item.created_at||item.updated_at)}${item.source==='legacy'?' · 기존 기록':''}`;$('submission-select').append(option);}showCode();
 }catch(error){$('detail-title').textContent='조회 실패';$('detail-summary').textContent=error.message;}
}
function showCode(){const item=choices[Number($('submission-select').value)];$('submission-report').replaceChildren();$('submission-code').textContent=item?.code||'아직 저장된 코드가 없습니다.';$('submission-meta').textContent=item?(item.source==='legacy'?'브라우저에 남아 있던 기록을 가져온 제출입니다.':item.kind==='draft'?'작성 중인 초안입니다. 채점 결과가 아닙니다.':'브라우저 자동채점 결과 · '+time(item.created_at)):'';if(item?.report?.error){const p=document.createElement('p');p.textContent=item.report.error;$('submission-report').append(p);}for(const row of item?.report?.rows||[]){const p=document.createElement('p');p.textContent=(row.ok?'✓':'✗')+' 검사 '+row.number+' '+row.message;$('submission-report').append(p);}}
$('submission-select').onchange=showCode;$('detail-close').onclick=()=>$('student-detail').close();
function passwordDialog(mode){passwordMode=mode;$('password-form').reset();$('password-error').textContent='';$('password-title').textContent=mode==='admin'?'관리자 비밀번호 변경':detail.student.name+' 학생 비밀번호 초기화';$('password-dialog').showModal();}
$('admin-change-password').onclick=()=>passwordDialog('admin');$('student-reset-password').onclick=()=>{if(detail?.student)passwordDialog('student');};$('password-cancel').onclick=()=>$('password-dialog').close();
$('password-form').onsubmit=async event=>{event.preventDefault();$('password-submit').disabled=true;try{await request(passwordMode==='admin'?'admin-password':'admin-reset',{password:$('new-password').value,...(passwordMode==='student'?{student_id:detail.student.id}:{})});$('password-dialog').close();if(passwordMode==='admin'){signOut();$('admin-login-error').textContent='비밀번호를 변경했습니다. 새 비밀번호로 로그인하세요.';}else $('detail-summary').textContent='학생 비밀번호를 변경했습니다. 새 비밀번호를 학생에게 개별 안내하세요.';}catch(error){$('password-error').textContent=error.message;}finally{$('password-submit').disabled=false;}};
$('admin-csv').onclick=()=>{const quote=value=>'"'+String(value).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const lines=[['반','학번','이름','해결 문제','총 문제','채점 제출','최근 활동'],...filtered().map(s=>[s.section,s.student_no,s.name,s.solved,12,s.attempts,s.last_seen])].map(row=>row.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+lines],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='알고리즘_진행현황_'+section+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
if(token){$('admin-login-panel').hidden=true;$('admin-workspace').hidden=false;refresh();}
