const $=id=>document.getElementById(id),API='https://tltrbkttwzvwghaplurl.supabase.co/functions/v1/algorithm-lab';
let token=sessionStorage.getItem('dju-algolab-admin')||'',offset=0,rows=[],generation=0;
function signout(){generation++;token='';rows=[];sessionStorage.removeItem('dju-algolab-admin');$('dashboard').hidden=true;$('login').hidden=false;for(const id of ['visits','pages','sources','chart','views','visitors','ips','start','updated'])$(id).replaceChildren();}
async function request(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action,...body}),signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok){if(r.status===401)signout();throw Error(data.error||'조회 실패');}return data;}
function table(id,data){$(id).replaceChildren();for(const row of data){const tr=document.createElement('tr');for(const value of row){const td=document.createElement('td');td.textContent=String(value??'');tr.append(td);}$(id).append(tr);}}
const date=value=>new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});
async function refresh(){const mine=++generation;$('error').textContent='';$('refresh').disabled=true;try{const days=Number($('days').value);const [s,v]=await Promise.all([request('admin-site-stats',{days}),request('admin-site-visits',{days,offset})]);if(mine!==generation)return;rows=v.visits;$('views').textContent=s.views.toLocaleString();$('visitors').textContent=s.visitors.toLocaleString();$('ips').textContent=s.ips.toLocaleString();table('pages',s.pages.map(p=>[p.path,p.views,p.visitors]));table('sources',s.sources.map(p=>[p.referrer||'직접 방문 / 유입 정보 없음',p.views]));table('visits',rows.map(r=>[date(r.visited_at),r.ip||'미확인 / 보관 기간 만료',r.path,r.referrer||'직접 방문',r.browser,r.device]));$('chart').replaceChildren();const max=Math.max(1,...s.days.map(d=>d.views));for(const day of s.days){const bar=document.createElement('div');bar.className='bar';bar.title=day.day+' · 조회 '+day.views+' / 고유 '+day.visitors;const count=document.createElement('span');count.textContent=day.views;const shape=document.createElement('i');shape.style.height=(day.views/max*100)+'px';const label=document.createElement('span');label.textContent=day.day.slice(5);bar.append(count,shape,label);$('chart').append(bar);}$('previous').disabled=offset===0;$('next').disabled=rows.length<100;$('page').textContent=String(offset/100+1);$('updated').textContent='갱신 '+date(new Date());$('start').textContent=s.first_record?'현재 보관 중인 첫 기록: '+date(s.first_record)+' · 도입 이전의 방문/IP는 소급 수집되지 않습니다.':'수집된 방문 기록이 아직 없습니다.';}catch(e){$('error').textContent=e.message;}finally{$('refresh').disabled=false;}}
$('login-form').onsubmit=async e=>{e.preventDefault();try{const result=await request('admin-login',{password:$('password').value});token=result.token;sessionStorage.setItem('dju-algolab-admin',token);$('password').value='';$('login').hidden=true;$('dashboard').hidden=false;await refresh();}catch(e){$('login-error').textContent=e.message;}};
$('logout').onclick=async()=>{try{await request('logout');}catch{}signout();};$('refresh').onclick=refresh;$('days').onchange=()=>{offset=0;refresh();};$('previous').onclick=()=>{offset=Math.max(0,offset-100);refresh();};$('next').onclick=()=>{offset+=100;refresh();};
$('csv').onclick=()=>{const escape=s=>'"'+String(s??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const data=[['접속시각','IP','페이지','유입','브라우저','기기'],...rows.map(r=>[date(r.visited_at),r.ip,r.path,r.referrer,r.browser,r.device])].map(r=>r.map(escape).join(',')).join('\r\n');const u=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='사이트접속기록.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
if(token){$('login').hidden=true;$('dashboard').hidden=false;refresh();}
